Repository jenkinsci/script-security-plugin, pull requests merged in 2021-05, with the labels that each got.

#345 Update plugin parent POM; use plugin BOM
  .mvn/extensions.xml
  pom.xml
Labels: dependencies

#346 Use native Java functionality rather than `com.google.common.collect`
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/RejectASTTransformsCustomizer.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptor.java
Labels: chore

#319 JENKINS-64057: Whitelist XmlUtil and a few java.util scripts
  src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Labels: enhancement

#348 [JEP-223] `RUN_SCRIPTS` → `ADMINISTER`
  src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalLink.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalNote.java
  src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScript/config.jelly
  src/main/resources/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval/index.jelly
  src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScriptTest.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalNoteTest.java
Labels: enhancement
