Repository jenkinsci/script-security-plugin, pull requests merged in 2022-04, with the labels that each got.

#411 Update plugin parent POM and BOM
  pom.xml
Labels: dependencies

#329 [JENKINS-62708] Add JCasC support for approved script hashes
  src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/JcascTest.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalTest.java
  src/test/resources/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalTest/upgradeSmokes/scriptApproval.xml
  src/test/resources/org/jenkinsci/plugins/scriptsecurity/scripts/smoke_test.yaml
  src/test/resources/org/jenkinsci/plugins/scriptsecurity/scripts/smoke_test_expected.yaml
Labels: enhancement

#405 Make a comment more inclusive
  src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/blacklist
Labels: chore

#400 Switch to Temurin distribution
  .github/workflows/cd.yaml
Labels: chore

#402 Whitelist net.sf.json.JSON isEmpty()
  src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Labels: enhancement

#408 Optimize the display of ScriptApproval page
  src/main/resources/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval/index.jelly
Labels: bug

#406 Refactoring / modernization
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/Whitelist.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyCallSiteSelector.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptor.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScript.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/EnumeratingWhitelist.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/ProxyWhitelist.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/StaticWhitelist.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScriptTest.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/EnumeratingWhitelistTest.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/StaticWhitelistTest.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/AbstractApprovalTest.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/EntryApprovalTest.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/Manager.java
Labels: chore

#401 Replace deprecated APIs
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScript.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ApprovalContext.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalNote.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyCallSiteSelectorTest.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxResolvingClassLoaderTest.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScriptTest.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/TestGroovyRecorder.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/StaticWhitelistTest.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/ClasspathEntryTest.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalNoteTest.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalTest.java
Labels: chore
