Repository jenkinsci/script-security-plugin, pull requests merged in 2022-01, with the labels that each got.

#380 EOL JSR 305
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/RejectedAccessException.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/Whitelist.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyCallSiteSelector.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovySandbox.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptor.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScript.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/AnnotatedWhitelist.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/EnumeratingWhitelist.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/StaticWhitelist.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ApprovalContext.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ClasspathEntry.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/Language.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
Labels: dependencies

#368 [JENKINS-66888] Whitelist `java.time.temporal.ChronoUnit.*`
  src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Labels: enhancement

#382 Bump parent, baseline, BOM
  pom.xml
Labels: dependencies

#365 JENKINS-66735: Whitelist some common signatures and additional signatures from `CauseOfInterruption`
  src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
  src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/jenkins-whitelist
Labels: enhancement

#383 Enforce use of `Outer$Inner` syntax in whitelists
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/EnumeratingWhitelist.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/EnumeratingWhitelistTest.java
Labels: tests
