Repository jenkinsci/script-security-plugin, pull requests merged in 2022-11, with the labels that each got.

#465 Never try to treat `URL.path` as a file path
  src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/HasherScriptApprovalTest.java
Labels: tests

#466 Never try to treat `URL.path` as a file path (backport)
  src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/HasherScriptApprovalTest.java
Labels: tests

#468 SpotBugs fix
  src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
Labels: chore

#467 Add Java 17 to test matrix (owner-filed)
  Jenkinsfile
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovySandbox.java
Labels: tests

#461 Add Java 17 to test matrix
  Jenkinsfile
Labels: tests

#459 Workaround for JDK-8231454 on Java 11 is no longer necessary as of 11.0.17
  pom.xml
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScript.java
Labels: developer

#298 [JENKINS-42214] SandboxInterceptor must account for static members being accessed via objects instead of class references
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptor.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/EnumeratingWhitelist.java
  src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/jenkins-whitelist
  src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/EnumeratingWhitelistTest.java
Labels: bug
