Repository jenkinsci/script-security-plugin, pull requests merged in 2023-08, with the labels that each got.

#520 Bump bom and baseline
  pom.xml
Labels: developer

#521 Update ScriptApprovalLink icon
  src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalLink.java
Labels: enhancement

#522 forward compatibility with core-8418
  src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScriptTest.java
  src/test/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/TestGroovyRecorder/config.jelly
Labels: test, developer
