Repository jenkinsci/script-security-plugin, pull requests merged in 2024-10, with the labels that each got.

#582 [JENKINS-69651] CSP compatibility for `ScriptApproval`
  src/main/resources/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval/deprecated-approvedClasspaths-clear-btn-hide.js
  src/main/resources/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval/deprecated-approvedClasspaths-clear-btn-show.js
  src/main/resources/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval/index.jelly
  src/main/resources/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval/script-approval.js
Labels: internal

#584 JENKINS-73941 - Option to hide "Use Groovy Sandbox" for users without Administer permission globally in the system
  README.md
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScript.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalNote.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/UnapprovedUsageException.java
  src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScript/config.jelly
  src/main/resources/org/jenkinsci/plugins/scriptsecurity/scripts/Messages.properties
  src/main/resources/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval/config.jelly
  src/main/resources/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval/help-forceSandbox.html
  src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScriptTest.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/JcascTest.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalTest.java
  src/test/resources/org/jenkinsci/plugins/scriptsecurity/scripts/smoke_test.yaml
  src/test/resources/org/jenkinsci/plugins/scriptsecurity/scripts/smoke_test_expected.yaml
Labels: enhancement

#585 JENKINS-73941 - ForceSandbox - Align Script-Security plugin with preexisting behavior in Workflow-CPS plugin
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScript.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
  src/main/resources/org/jenkinsci/plugins/scriptsecurity/scripts/Messages.properties
  src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SecureGroovyScriptTest.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalTest.java
Labels: bug
