Repository jenkinsci/script-security-plugin, pull requests merged in 2024-01, with the labels that each got.

#549 Overhauled `ProxyWhitelist`
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/AclAwareWhitelist.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/EnumeratingWhitelist.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/GenericWhitelist.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/JenkinsWhitelist.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/ProxyWhitelist.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/StaticWhitelist.java
  src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/EnumeratingWhitelistTest.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/GenericWhitelistTest.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/JenkinsWhitelistTest.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/ProxyWhitelistTest.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalTest.java
Labels: bug

#551 Remove word duplication from Script Security UI
  src/main/resources/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval/index.jelly
Labels: documentation

#550 add badge
  src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalLink.java
  src/main/resources/org/jenkinsci/plugins/scriptsecurity/scripts/Messages.properties
Labels: enhancement

#552 `ExtensionList` error after dynamic load
  src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalLoadingTest.java
Labels: bug

#553 Skip `ScriptApprovalLoadingTest` in PCT
  pom.xml
  src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalLoadingTest.java
Labels: developer
