Repository jenkinsci/script-security-plugin, pull requests merged in 2024-02, with the labels that each got.

#555 Avoid race condition in `ApprovedWhitelist` reconfiguration
  Jenkinsfile
  src/main/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApproval.java
  src/test/java/org/jenkinsci/plugins/scriptsecurity/scripts/ScriptApprovalTest.java
Labels: bug

#556 Restore Windows branch in PRs
  Jenkinsfile
Labels: tests

#559 Bump plugin parent pom to 4.78
  pom.xml
Labels: developer
