Repository jenkinsci/script-security-plugin, pull requests merged in 2024-09, with the labels that each got.

#577 Also add `DateTimeFormatter` `ofPattern` with `Locale`-parameter to the whitelist
  src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/generic-whitelist
Labels: enhancement

#576 Whitelist method moved from `Run#getFullDisplayName` to `HistoricalBuild#getFullDisplayName`
  src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/jenkins-whitelist
  src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/StaticWhitelistTest.java
Labels: bug

#578 Fix JenkinsWhitelistTest on 2.477 incremental
  src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/StaticWhitelistTest.java
Labels: test, developer
